services:
  - type: web
    name: jobjet-ai
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
value 7883161984:AAF_T1IMahf_EYS421imVzfW-5NGuyNu0Qk
