services:
  - type: web
    name: jobjet-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_BASE_URL
        sync: false
